services:
  trafficjam:
    container_name: trafficjam
    image: kaysond/trafficjam
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: unless-stopped
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
      NETWORK: proxy
      WHITELIST_FILTER: ancestor=traefik:latest
      TZ: Europe/Berlin

  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - internal
      - proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_API_EMAIL=CHANGE_ME # ⚠️
      - CF_DNS_API_TOKEN=CHANGE_ME # ⚠️
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/traefik.yml:ro
      - ./config/config.yml:/config.yml:ro
      - ./data/acme.json:/acme.json
      - ./data/logs:/var/log/traefik
    labels:
      - "traefik.enable=true"

networks:
  internal:
  proxy:
    external: true